"on":
    push:
        branches:
            - main
name: Deploy to studio-220
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: studio-220
                PORTER_CLUSTER: "661"
                PORTER_DEPLOYMENT_TARGET_ID: 00152bdf-33dd-44fe-b0e4-94a32fc2f92b
                PORTER_HOST: https://dashboard.internal-tools.porter.run
                PORTER_PROJECT: "523"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_523_766 }}
